project_id = "qaqmlmshpifwdnrvfkao"

[functions.delete-user]
verify_jwt = true

[functions.generate-templates]
verify_jwt = false

[functions.razorpay-webhook]
verify_jwt = false

[functions.warm-demand-cache]
verify_jwt = false