project_id = "qaqmlmshpifwdnrvfkao"

[functions.delete-user]
verify_jwt = true

[functions.generate-templates]
verify_jwt = false

[functions.razorpay-webhook]
verify_jwt = false

[functions.support-chat]
verify_jwt = false

[functions.warm-demand-cache]
verify_jwt = false

[functions.agora-tokens]
verify_jwt = true

[functions.admin-create-user]
verify_jwt = true